export const ALERT_MESSAGE = 'ALERT_MESSAGE'
export const SHOW_LOADER = 'SHOW_LOADER'
export const HIDE_LOADER = 'HIDE_LOADER'

export const SELECT_GAME = 'SELECT_GAME'
export const SET_GAME_LIST = 'SET_GAME_LIST'
export const SET_GAME_STEPS = 'SET_GAME_STEPS'

export const FIGURE_MOVED = 'FIGURE_MOVED'

export const MULTIPLAYER_LIST_HEARTBEAT = 'MULTIPLAYER_LIST_HEARTBEAT'
export const MULTIPLAYER_CREATE_GAME = 'MULTIPLAYER_CREATE_GAME'
export const MULTIPLAYER_START_GAME = 'MULTIPLAYER_START_GAME'
export const MULTIPLAYER_FLAG_GAME = 'MULTIPLAYER_FLAG_GAME'
export const MULTIPLAYER_GAME_HEARTBEAT = 'MULTIPLAYER_GAME_HEARTBEAT'
export const MULTIPLAYER_GAME_SEND_STEP = 'MULTIPLAYER_GAME_SEND_STEP'
